name: Build Windows Portable

on:
  push:
    branches: [ main, testing ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # removed "cache: npm" because no package-lock.json exists

      - name: Show environment info
        run: |
          node -v
          np
